### ISSUE TITLE
mev-inspect fails to inspect block 13486138

### ISSUE THREAD

**Issue by lukevs** [flashbots/mev-inspect-py#145]
Block 13486138 contains some swaps with a protocol BankETH
https://etherscan.io/tx/0x08fdd7cb5fb68cb41fb740362c3f98116d37c6b1234314b81a394fcc81a90099

It's getting parsed as an arbitrage with the same swap happening twice which then fails to write to the DB

## Replicate
```
./mev inspect 13486138
```

**Comment by gheise** [comment]
This also occurs on block 13750068, transaction 0xcd360c9085191c24c5346226dbbf04f5d93e00be616b972c1c560747fa7eb954
