### ISSUE TITLE
cannot run backfill

### ISSUE THREAD

**Issue by simple4016** [flashbots/mev-inspect-py#155]
i can run all the others except the backfill.
when run backfill:
<img width="1917" alt="CleanShot 2021-12-10 at 11 44 54@2x" src="https://user-images.githubusercontent.com/5715598/145513831-6339f1e5-34a1-4dc1-8620-e730514014c6.png">

**Comment by lukevs** [comment]
Hmm it looks like the pod is maybe loading a pre-python 3.5 version

Are you using the full kubernetes / tilt setup?

**Comment by simple4016** [comment]
> Hmm it looks like the pod is maybe loading a pre-python 3.5 version
> 
> Are you using the full kubernetes / tilt setup?

thanks for your reply.

i go step by step in the Readme.

**Comment by lukevs** [comment]
If you run
```
./mev exec python --version
```
what do you see?

**Comment by simple4016** [comment]
Python 3.9.9

**Comment by lukevs** [comment]
We were using the default python instead of poetry installed python for the backfill script

This PR fixes the issue: https://github.com/flashbots/mev-inspect-py/pull/200

**Comment by lukevs** [comment]
Fixed - Thanks @simple4016 for reporting!
