### ISSUE TITLE
Create data model for tables + insert/update functions in utils

### ISSUE THREAD

**Issue by taarushv** [flashbots/mev-inspect-py#16]

**Comment by mattsse** [comment]
fyi: i did some additional work on this PR https://github.com/flashbots/mev-inspect-rs/pull/59 including tables and sql migrations https://github.com/mattsse/mev-inspect-rs/blob/new-database-model-and-inspect-reduce-api/migrations/00000000000000_initial_setup/up.sql

**Comment by lukevs** [comment]
This issue is solved by our schemas in `mev_inspect/schemas`, DB models in `mev_inspect/models`, and migrations in alembic
