### ISSUE TITLE
listener problem

### ISSUE THREAD

**Issue by soloblack** [flashbots/mev-inspect-py#172]
![image](https://user-images.githubusercontent.com/8198350/146795341-fbb5bc1a-93f6-4b22-92e7-d4c4496307c6.png)

./mev inspect 12914944 is work

RPC_URL is provided by pokt.network

**Comment by lukevs** [comment]
This None issue is now fixed as of https://github.com/flashbots/mev-inspect-py/pull/174

Please let me know if you're still seeing issues!

**Comment by soloblack** [comment]
It works, thank you
