### ISSUE TITLE
Sandwiches incorrectly filters out Uniswap accidental sandwiches

### ISSUE THREAD

**Issue by Dire-0x** [flashbots/mev-inspect-py#280]
The `sandwich.sandwicher_address` should not be Uniswap V2 Router, V3 Router, or V3 Router 2. 

The current check on the Uniswap V2 Router is `0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D` when it should be `0x7a250d5630b4cf539739df2c5dacb4c659f2488d`

The Uniswap V3 Router being checked is actually the Uniswap V3 Router 2, the Uniswap V3 Router should be added

**Comment by lukevs** [comment]
Thanks!
