### ISSUE TITLE
Finalize architecture

### ISSUE THREAD

**Issue by bertmiller** [flashbots/mev-inspect-py#3]
In particular we need to answer these questions:
- Should profit estimation happen at the inspector level? Or elsewhere?
- Is it _possible_ to use one script, e.g. an analysis of what tokens flowed in and out of a transaction, to estimate profit?
- Where and when are we posting data to the database?

**Comment by rencryptofish** [comment]
we probably would want to async each inspector

**Comment by rencryptofish** [comment]
might also need a pricer if we want to handle more than just eth denom arbs (something like given a token address, retrieve on chain price)

**Comment by bertmiller** [comment]
Totally agree, are you interested in helping build that @rencryptofish?
