### ISSUE TITLE
Why failed transactions are written to the database?

### ISSUE THREAD

**Issue by ocoderr** [flashbots/mev-inspect-py#301]
run  
poetry run inspect-block 14829265

Found 2 sandwiches

one  frontrun transaction and backrun transaction is failure on chain 
frontrun: 0x8c5c6d77a2d4c9a555e6694db25da2eec59681eac3010434bbcc02b1a3f86402
https://etherscan.io/tx/0x8c5c6d77a2d4c9a555e6694db25da2eec59681eac3010434bbcc02b1a3f86402

backrun: 0xfae3f7897fa46fac2c4ef2322ae7aef5478ba7d19cd08bc4bbdd4d608e90bd8d
https://etherscan.io/tx/0xfae3f7897fa46fac2c4ef2322ae7aef5478ba7d19cd08bc4bbdd4d608e90bd8d

Should it exclude failed transactions?

**Comment by gheise** [comment]
We include failed transactions to supply data about the impacts of transaction failure on profits and strategies. Thank you for highlighting this!
