### ISSUE TITLE
Random failures with ValueError: {'message': 'Internal JSON-RPC error.', 'code': -32603}

### ISSUE THREAD

**Issue by marsupialtail** [flashbots/mev-inspect-py#308]
Thanks for this great project.
I installed this project and tried to do ./mev inspect 12914944. I am using the RPC endpoint on Pokt as recommended.
Sometimes I can get it to work and dump to the postgres, sometime I get this error:
  File "/app/mev_inspect/block.py", line 115, in _fetch_block_traces
    traces_json = await w3.eth.trace_block(block_number)
  File "/home/flashbot/.local/lib/python3.9/site-packages/web3/module.py", line 72, in caller
    result = await w3.manager.coro_request(method_str,
  File "/home/flashbot/.local/lib/python3.9/site-packages/web3/manager.py", line 203, in coro_request
    return self.formatted_response(response,
  File "/home/flashbot/.local/lib/python3.9/site-packages/web3/manager.py", line 168, in formatted_response
    raise ValueError(response["error"])
ValueError: {'message': 'Internal JSON-RPC error.', 'code': -32603}
command terminated with exit code 1

It is truly random -- all it takes for error to go away is to run the command again.
What is going on here?

**Comment by zhanzekun** [comment]
I met this problem too and it occurs everytime when I  run "./mev inspect 12914944"

**Comment by gheise** [comment]
This an internal error from Pokt's node. Feel free to refer to their support team or documentation for a solution, we unfortunately do not have additional details about errors originating on their platform
